import type { Benefit, Chain, Company, CompanySize, CompanyType, Scene } from "./types";

export type AtsKind = "greenhouse" | "lever" | "ashby";

export type LiveBoard = {
  id: string;
  name: string;
  ats: AtsKind;
  board: string;
  website: string;
  careers: string;
  twitter: string;
  github: string;
  applyHosts: string[];
  scenes: Scene[];
  chains: Chain[];
  size: CompanySize;
  type: CompanyType;
  hq: string;
  remotePolicy: Company["remotePolicy"];
  foundedYear: number;
  ticker?: string;
  about: string;
  hue: number;
  benefits: Benefit[];
};

const B = (partial: LiveBoard): LiveBoard => partial;

/** First-party career hosts plus the three ATS hosts we fetch from. */
export const ATS_APPLY_HOSTS = new Set([
  "jobs.lever.co",
  "jobs.ashbyhq.com",
  "job-boards.greenhouse.io",
  "job-boards.eu.greenhouse.io",
  "boards.greenhouse.io",
  "boards.eu.greenhouse.io",
]);

export const BOARDS: LiveBoard[] = [
  B({
    id: "coinbase",
    name: "Coinbase",
    ats: "greenhouse",
    board: "coinbase",
    website: "https://www.coinbase.com",
    careers: "https://www.coinbase.com/careers",
    twitter: "https://x.com/coinbase",
    github: "https://github.com/coinbase",
    applyHosts: ["www.coinbase.com", "coinbase.com"],
    scenes: ["crypto"],
    chains: ["bitcoin", "ethereum", "solana", "base", "multi-chain"],
    size: "1000+",
    type: "exchange",
    hq: "San Francisco",
    remotePolicy: "remote-first",
    foundedYear: 2012,
    ticker: "COIN",
    about: "Public US exchange and the team behind Base. Listings are live from Coinbase’s Greenhouse board.",
    hue: 220,
    benefits: ["remote-first", "healthcare", "visa-sponsorship", "parental-leave", "unlimited-pto"],
  }),
  B({
    id: "binance",
    name: "Binance",
    ats: "lever",
    board: "binance",
    website: "https://www.binance.com",
    careers: "https://www.binance.com/en/careers",
    twitter: "https://x.com/binance",
    github: "https://github.com/binance",
    applyHosts: ["www.binance.com", "binance.com"],
    scenes: ["crypto"],
    chains: ["bnb", "bitcoin", "ethereum", "multi-chain"],
    size: "1000+",
    type: "exchange",
    hq: "Remote",
    remotePolicy: "remote-first",
    foundedYear: 2017,
    about: "Largest crypto exchange by volume. Listings are live from Binance’s Lever board.",
    hue: 42,
    benefits: ["remote-first", "healthcare", "unlimited-pto"],
  }),
  B({
    id: "okx",
    name: "OKX",
    ats: "greenhouse",
    board: "okx",
    website: "https://www.okx.com",
    careers: "https://www.okx.com/careers",
    twitter: "https://x.com/okx",
    github: "https://github.com/okx",
    applyHosts: ["www.okx.com", "okx.com"],
    scenes: ["crypto"],
    chains: ["bitcoin", "ethereum", "solana", "multi-chain"],
    size: "1000+",
    type: "exchange",
    hq: "Singapore",
    remotePolicy: "hybrid",
    foundedYear: 2017,
    about: "Global exchange and wallet. Listings are live from OKX’s Greenhouse board.",
    hue: 168,
    benefits: ["healthcare", "remote-first"],
  }),
  B({
    id: "bybit",
    name: "Bybit",
    ats: "greenhouse",
    board: "bybit",
    website: "https://www.bybit.com",
    careers: "https://www.bybit.com/en/careers",
    twitter: "https://x.com/Bybit_Official",
    github: "https://github.com/bybit-exchange",
    applyHosts: [],
    scenes: ["crypto"],
    chains: ["bitcoin", "ethereum", "multi-chain"],
    size: "1000+",
    type: "exchange",
    hq: "Dubai",
    remotePolicy: "hybrid",
    foundedYear: 2018,
    about: "Derivatives-first exchange. Listings are live from Bybit’s Greenhouse board.",
    hue: 28,
    benefits: ["healthcare", "remote-first"],
  }),
  B({
    id: "ripple",
    name: "Ripple",
    ats: "greenhouse",
    board: "ripple",
    website: "https://ripple.com",
    careers: "https://ripple.com/careers",
    twitter: "https://x.com/Ripple",
    github: "https://github.com/ripple",
    applyHosts: ["ripple.com", "www.ripple.com"],
    scenes: ["crypto", "infrastructure"],
    chains: ["multi-chain"],
    size: "1000+",
    type: "infrastructure",
    hq: "San Francisco",
    remotePolicy: "hybrid",
    foundedYear: 2012,
    ticker: "XRP",
    about: "Payments and digital-asset infrastructure on the XRP Ledger. Listings are live from Ripple’s Greenhouse board.",
    hue: 200,
    benefits: ["healthcare", "visa-sponsorship", "parental-leave"],
  }),
  B({
    id: "kraken",
    name: "Kraken",
    ats: "ashby",
    board: "kraken.com",
    website: "https://www.kraken.com",
    careers: "https://www.kraken.com/careers",
    twitter: "https://x.com/krakenfx",
    github: "https://github.com/krakenfx",
    applyHosts: ["www.kraken.com", "kraken.com"],
    scenes: ["crypto"],
    chains: ["bitcoin", "ethereum", "solana", "multi-chain"],
    size: "1000+",
    type: "exchange",
    hq: "San Francisco",
    remotePolicy: "remote-first",
    foundedYear: 2011,
    about: "US-founded exchange. Listings are live from Kraken’s Ashby board.",
    hue: 18,
    benefits: ["remote-first", "healthcare", "unlimited-pto"],
  }),
  B({
    id: "fireblocks",
    name: "Fireblocks",
    ats: "greenhouse",
    board: "fireblocks",
    website: "https://www.fireblocks.com",
    careers: "https://www.fireblocks.com/careers",
    twitter: "https://x.com/FireblocksHQ",
    github: "https://github.com/fireblocks",
    applyHosts: ["www.fireblocks.com", "fireblocks.com"],
    scenes: ["crypto", "infrastructure"],
    chains: ["bitcoin", "ethereum", "multi-chain"],
    size: "201-1000",
    type: "infrastructure",
    hq: "New York",
    remotePolicy: "hybrid",
    foundedYear: 2018,
    about: "MPC custody and settlement for institutions. Listings are live from Fireblocks’ Greenhouse board.",
    hue: 255,
    benefits: ["healthcare", "visa-sponsorship", "parental-leave"],
  }),
  B({
    id: "cryptocom",
    name: "Crypto.com",
    ats: "lever",
    board: "crypto",
    website: "https://crypto.com",
    careers: "https://crypto.com/careers",
    twitter: "https://x.com/cryptocom",
    github: "https://github.com/crypto-com",
    applyHosts: ["crypto.com", "www.crypto.com"],
    scenes: ["crypto"],
    chains: ["ethereum", "bitcoin", "multi-chain"],
    size: "1000+",
    type: "exchange",
    hq: "Singapore",
    remotePolicy: "hybrid",
    foundedYear: 2016,
    ticker: "CRO",
    about: "Consumer exchange, card, and app. Listings are live from Crypto.com’s Lever board.",
    hue: 350,
    benefits: ["healthcare", "remote-first"],
  }),
  B({
    id: "chainalysis",
    name: "Chainalysis",
    ats: "ashby",
    board: "chainalysis-careers",
    website: "https://www.chainalysis.com",
    careers: "https://www.chainalysis.com/careers",
    twitter: "https://x.com/chainalysis",
    github: "https://github.com/chainalysis",
    applyHosts: ["www.chainalysis.com", "chainalysis.com"],
    scenes: ["crypto", "infrastructure"],
    chains: ["bitcoin", "ethereum", "multi-chain"],
    size: "201-1000",
    type: "other",
    hq: "New York",
    remotePolicy: "hybrid",
    foundedYear: 2014,
    about: "Blockchain investigation and compliance data. Listings are live from Chainalysis’ Ashby board.",
    hue: 12,
    benefits: ["healthcare", "visa-sponsorship", "parental-leave"],
  }),
  B({
    id: "blockchaincom",
    name: "Blockchain.com",
    ats: "greenhouse",
    board: "blockchain",
    website: "https://www.blockchain.com",
    careers: "https://www.blockchain.com/careers",
    twitter: "https://x.com/blockchain",
    github: "https://github.com/blockchain",
    applyHosts: ["www.blockchain.com", "blockchain.com"],
    scenes: ["crypto"],
    chains: ["bitcoin", "ethereum", "multi-chain"],
    size: "201-1000",
    type: "exchange",
    hq: "London",
    remotePolicy: "hybrid",
    foundedYear: 2011,
    about: "Wallet, exchange, and data since 2011. Listings are live from Blockchain.com’s Greenhouse board.",
    hue: 145,
    benefits: ["healthcare", "visa-sponsorship"],
  }),
  B({
    id: "bitgo",
    name: "BitGo",
    ats: "greenhouse",
    board: "bitgo",
    website: "https://www.bitgo.com",
    careers: "https://www.bitgo.com/company/careers",
    twitter: "https://x.com/BitGo",
    github: "https://github.com/BitGo",
    applyHosts: ["www.bitgo.com", "bitgo.com"],
    scenes: ["crypto", "infrastructure"],
    chains: ["bitcoin", "ethereum", "multi-chain"],
    size: "201-1000",
    type: "infrastructure",
    hq: "Palo Alto",
    remotePolicy: "hybrid",
    foundedYear: 2013,
    about: "Qualified custody and settlement. Listings are live from BitGo’s Greenhouse board.",
    hue: 190,
    benefits: ["healthcare", "visa-sponsorship"],
  }),
  B({
    id: "gemini",
    name: "Gemini",
    ats: "greenhouse",
    board: "gemini",
    website: "https://www.gemini.com",
    careers: "https://www.gemini.com/careers",
    twitter: "https://x.com/gemini",
    github: "https://github.com/gemini",
    applyHosts: ["www.gemini.com", "gemini.com"],
    scenes: ["crypto"],
    chains: ["bitcoin", "ethereum", "solana", "multi-chain"],
    size: "201-1000",
    type: "exchange",
    hq: "New York",
    remotePolicy: "hybrid",
    foundedYear: 2014,
    about: "NY-regulated exchange. Listings are live from Gemini’s Greenhouse board.",
    hue: 55,
    benefits: ["healthcare", "parental-leave", "visa-sponsorship"],
  }),
  B({
    id: "alchemy",
    name: "Alchemy",
    ats: "ashby",
    board: "alchemy",
    website: "https://www.alchemy.com",
    careers: "https://www.alchemy.com/careers",
    twitter: "https://x.com/Alchemy",
    github: "https://github.com/alchemyplatform",
    applyHosts: ["www.alchemy.com", "alchemy.com"],
    scenes: ["infrastructure"],
    chains: ["ethereum", "polygon", "arbitrum", "base", "multi-chain"],
    size: "201-1000",
    type: "infrastructure",
    hq: "San Francisco",
    remotePolicy: "remote-first",
    foundedYear: 2017,
    about: "Node, data, and developer platform. Listings are live from Alchemy’s Ashby board.",
    hue: 270,
    benefits: ["remote-first", "healthcare", "unlimited-pto"],
  }),
  B({
    id: "phantom",
    name: "Phantom",
    ats: "ashby",
    board: "phantom",
    website: "https://phantom.com",
    careers: "https://phantom.com/jobs",
    twitter: "https://x.com/phantom",
    github: "https://github.com/phantom",
    applyHosts: ["phantom.com", "www.phantom.com"],
    scenes: ["crypto"],
    chains: ["solana", "ethereum", "bitcoin", "base", "polygon"],
    size: "51-200",
    type: "consumer",
    hq: "San Francisco",
    remotePolicy: "remote-first",
    foundedYear: 2021,
    about: "Self-custody wallet, starting on Solana. Listings are live from Phantom’s Ashby board.",
    hue: 280,
    benefits: ["remote-first", "healthcare", "unlimited-pto"],
  }),
  B({
    id: "circle",
    name: "Circle",
    ats: "ashby",
    board: "circle",
    website: "https://www.circle.com",
    careers: "https://www.circle.com/careers",
    twitter: "https://x.com/circle",
    github: "https://github.com/circlefin",
    applyHosts: ["www.circle.com", "circle.com"],
    scenes: ["crypto"],
    chains: ["ethereum", "solana", "base", "multi-chain"],
    size: "201-1000",
    type: "infrastructure",
    hq: "Boston",
    remotePolicy: "hybrid",
    foundedYear: 2013,
    ticker: "CRCL",
    about: "Issuer of USDC. Listings are live from Circle’s Ashby board.",
    hue: 205,
    benefits: ["healthcare", "visa-sponsorship", "parental-leave"],
  }),
  B({
    id: "uniswap",
    name: "Uniswap Labs",
    ats: "ashby",
    board: "uniswap",
    website: "https://uniswap.org",
    careers: "https://jobs.ashbyhq.com/uniswap",
    twitter: "https://x.com/Uniswap",
    github: "https://github.com/Uniswap",
    applyHosts: ["uniswap.org", "www.uniswap.org"],
    scenes: ["defi"],
    chains: ["ethereum", "base", "arbitrum", "optimism", "polygon"],
    size: "51-200",
    type: "protocol",
    hq: "New York",
    remotePolicy: "remote-first",
    foundedYear: 2018,
    ticker: "UNI",
    about: "Team behind the Uniswap protocol and app. Listings are live from Uniswap Labs’ Ashby board.",
    hue: 310,
    benefits: ["remote-first", "token-vesting", "healthcare"],
  }),
  B({
    id: "ledger",
    name: "Ledger",
    ats: "ashby",
    board: "ledger",
    website: "https://www.ledger.com",
    careers: "https://www.ledger.com/careers",
    twitter: "https://x.com/Ledger",
    github: "https://github.com/LedgerHQ",
    applyHosts: ["www.ledger.com", "ledger.com"],
    scenes: ["crypto"],
    chains: ["bitcoin", "ethereum", "solana", "multi-chain"],
    size: "201-1000",
    type: "consumer",
    hq: "Paris",
    remotePolicy: "hybrid",
    foundedYear: 2014,
    about: "Hardware wallets and Ledger Live. Listings are live from Ledger’s Ashby board.",
    hue: 110,
    benefits: ["healthcare", "parental-leave"],
  }),
  B({
    id: "consensys",
    name: "Consensys",
    ats: "greenhouse",
    board: "consensys",
    website: "https://consensys.io",
    careers: "https://consensys.io/open-roles",
    twitter: "https://x.com/Consensys",
    github: "https://github.com/ConsenSys",
    applyHosts: ["consensys.io", "www.consensys.io"],
    scenes: ["crypto", "infrastructure"],
    chains: ["ethereum", "multi-chain"],
    size: "201-1000",
    type: "infrastructure",
    hq: "New York",
    remotePolicy: "remote-first",
    foundedYear: 2014,
    about: "MetaMask, Infura, and Linea. Listings are live from Consensys’ Greenhouse board.",
    hue: 330,
    benefits: ["remote-first", "healthcare", "token-vesting"],
  }),
  B({
    id: "ethereumfoundation",
    name: "Ethereum Foundation",
    ats: "ashby",
    board: "ethereum-foundation",
    website: "https://ethereum.foundation",
    careers: "https://jobs.ashbyhq.com/ethereum-foundation",
    twitter: "https://x.com/ethereum",
    github: "https://github.com/ethereum",
    applyHosts: ["ethereum.foundation", "ethereum.org"],
    scenes: ["infrastructure"],
    chains: ["ethereum"],
    size: "51-200",
    type: "research",
    hq: "Remote",
    remotePolicy: "remote-first",
    foundedYear: 2014,
    ticker: "ETH",
    about: "Nonprofit supporting Ethereum. Listings are live from the Foundation’s Ashby board.",
    hue: 250,
    benefits: ["remote-first", "flexible-hours"],
  }),
  B({
    id: "solanalabs",
    name: "Solana Labs",
    ats: "ashby",
    board: "solanalabs",
    website: "https://solana.com",
    careers: "https://jobs.ashbyhq.com/solanalabs",
    twitter: "https://x.com/solana",
    github: "https://github.com/solana-labs",
    applyHosts: ["solana.com", "www.solana.com"],
    scenes: ["infrastructure"],
    chains: ["solana"],
    size: "51-200",
    type: "protocol",
    hq: "San Francisco",
    remotePolicy: "remote-first",
    foundedYear: 2018,
    ticker: "SOL",
    about: "Core engineering for Solana and Solana Mobile. Listings are live from Solana Labs’ Ashby board.",
    hue: 160,
    benefits: ["remote-first", "token-vesting", "healthcare"],
  }),
];

export const BOARD_BY_ID = new Map(BOARDS.map((b) => [b.id, b]));
export const COMPANY_IDS = BOARDS.map((b) => b.id);

export const COMPANIES: Company[] = BOARDS.map((b) => ({
  id: b.id,
  slug: b.id,
  name: b.name,
  logo: `/logos/${b.id}.png`,
  website: b.website,
  twitter: b.twitter,
  github: b.github,
  discord: "",
  scenes: b.scenes,
  chains: b.chains,
  size: b.size,
  type: b.type,
  hq: b.hq,
  remotePolicy: b.remotePolicy,
  verified: true,
  foundedYear: b.foundedYear,
  about: b.about,
  tokenTicker: b.ticker,
  benefits: b.benefits,
  hue: b.hue,
}));
