/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApplyJobSlugRouteImport } from './routes/apply/$jobSlug'
import { Route as ChainsSlugRouteImport } from './routes/chains/$slug'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'
import { Route as ContractsIndexRouteImport } from './routes/contracts/index'
import { Route as ContractsSlugRouteImport } from './routes/contracts/$slug'
import { Route as DepartmentsSlugRouteImport } from './routes/departments/$slug'
import { Route as GigsIndexRouteImport } from './routes/gigs/index'
import { Route as GigsSlugRouteImport } from './routes/gigs/$slug'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugRouteImport } from './routes/locations/$slug'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as MeProfileRouteImport } from './routes/me/profile'
import { Route as PostIndexRouteImport } from './routes/post/index'
import { Route as PostContractRouteImport } from './routes/post/contract'
import { Route as PostGigRouteImport } from './routes/post/gig'
import { Route as PostRoleRouteImport } from './routes/post/role'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as RolesSlugRouteImport } from './routes/roles/$slug'
import { Route as SalariesIndexRouteImport } from './routes/salaries/index'
import { Route as SalariesSlugRouteImport } from './routes/salaries/$slug'
import { Route as ScenesSlugRouteImport } from './routes/scenes/$slug'
import { Route as TalentIndexRouteImport } from './routes/talent/index'
import { Route as TalentSlugRouteImport } from './routes/talent/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobSlugRoute = ApplyJobSlugRouteImport.update({
  id: '/apply/$jobSlug',
  path: '/apply/$jobSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsSlugRoute = ChainsSlugRouteImport.update({
  id: '/chains/$slug',
  path: '/chains/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsSlugRoute = ContractsSlugRouteImport.update({
  id: '/contracts/$slug',
  path: '/contracts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/departments/$slug',
  path: '/departments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIndexRoute = GigsIndexRouteImport.update({
  id: '/gigs/',
  path: '/gigs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsSlugRoute = GigsSlugRouteImport.update({
  id: '/gigs/$slug',
  path: '/gigs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostContractRoute = PostContractRouteImport.update({
  id: '/post/contract',
  path: '/post/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const PostGigRoute = PostGigRouteImport.update({
  id: '/post/gig',
  path: '/post/gig',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoleRoute = PostRoleRouteImport.update({
  id: '/post/role',
  path: '/post/role',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesSlugRoute = RolesSlugRouteImport.update({
  id: '/roles/$slug',
  path: '/roles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesIndexRoute = SalariesIndexRouteImport.update({
  id: '/salaries/',
  path: '/salaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesSlugRoute = SalariesSlugRouteImport.update({
  id: '/salaries/$slug',
  path: '/salaries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesSlugRoute = ScenesSlugRouteImport.update({
  id: '/scenes/$slug',
  path: '/scenes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentSlugRoute = TalentSlugRouteImport.update({
  id: '/talent/$slug',
  path: '/talent/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/apply/$jobSlug': typeof ApplyJobSlugRoute
  '/chains/$slug': typeof ChainsSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/contracts/$slug': typeof ContractsSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/gigs/$slug': typeof GigsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/me/profile': typeof MeProfileRoute
  '/post/contract': typeof PostContractRoute
  '/post/gig': typeof PostGigRoute
  '/post/role': typeof PostRoleRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/salaries/$slug': typeof SalariesSlugRoute
  '/scenes/$slug': typeof ScenesSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/me/': typeof MeIndexRoute
  '/post/': typeof PostIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/salaries/': typeof SalariesIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/apply/$jobSlug': typeof ApplyJobSlugRoute
  '/chains/$slug': typeof ChainsSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/contracts/$slug': typeof ContractsSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/gigs/$slug': typeof GigsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/me/profile': typeof MeProfileRoute
  '/post/contract': typeof PostContractRoute
  '/post/gig': typeof PostGigRoute
  '/post/role': typeof PostRoleRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/salaries/$slug': typeof SalariesSlugRoute
  '/scenes/$slug': typeof ScenesSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/companies': typeof CompaniesIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/gigs': typeof GigsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/me': typeof MeIndexRoute
  '/post': typeof PostIndexRoute
  '/roles': typeof RolesIndexRoute
  '/salaries': typeof SalariesIndexRoute
  '/talent': typeof TalentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/apply/$jobSlug': typeof ApplyJobSlugRoute
  '/chains/$slug': typeof ChainsSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/contracts/$slug': typeof ContractsSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/gigs/$slug': typeof GigsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/me/profile': typeof MeProfileRoute
  '/post/contract': typeof PostContractRoute
  '/post/gig': typeof PostGigRoute
  '/post/role': typeof PostRoleRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/salaries/$slug': typeof SalariesSlugRoute
  '/scenes/$slug': typeof ScenesSlugRoute
  '/talent/$slug': typeof TalentSlugRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/me/': typeof MeIndexRoute
  '/post/': typeof PostIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/salaries/': typeof SalariesIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/login'
    | '/privacy'
    | '/pulse'
    | '/search'
    | '/studio'
    | '/terms'
    | '/apply/$jobSlug'
    | '/chains/$slug'
    | '/companies/$slug'
    | '/contracts/$slug'
    | '/departments/$slug'
    | '/gigs/$slug'
    | '/learn/$slug'
    | '/locations/$slug'
    | '/me/profile'
    | '/post/contract'
    | '/post/gig'
    | '/post/role'
    | '/roles/$slug'
    | '/salaries/$slug'
    | '/scenes/$slug'
    | '/talent/$slug'
    | '/companies/'
    | '/contracts/'
    | '/gigs/'
    | '/learn/'
    | '/locations/'
    | '/me/'
    | '/post/'
    | '/roles/'
    | '/salaries/'
    | '/talent/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/login'
    | '/privacy'
    | '/pulse'
    | '/search'
    | '/studio'
    | '/terms'
    | '/apply/$jobSlug'
    | '/chains/$slug'
    | '/companies/$slug'
    | '/contracts/$slug'
    | '/departments/$slug'
    | '/gigs/$slug'
    | '/learn/$slug'
    | '/locations/$slug'
    | '/me/profile'
    | '/post/contract'
    | '/post/gig'
    | '/post/role'
    | '/roles/$slug'
    | '/salaries/$slug'
    | '/scenes/$slug'
    | '/talent/$slug'
    | '/companies'
    | '/contracts'
    | '/gigs'
    | '/learn'
    | '/locations'
    | '/me'
    | '/post'
    | '/roles'
    | '/salaries'
    | '/talent'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/login'
    | '/privacy'
    | '/pulse'
    | '/search'
    | '/studio'
    | '/terms'
    | '/apply/$jobSlug'
    | '/chains/$slug'
    | '/companies/$slug'
    | '/contracts/$slug'
    | '/departments/$slug'
    | '/gigs/$slug'
    | '/learn/$slug'
    | '/locations/$slug'
    | '/me/profile'
    | '/post/contract'
    | '/post/gig'
    | '/post/role'
    | '/roles/$slug'
    | '/salaries/$slug'
    | '/scenes/$slug'
    | '/talent/$slug'
    | '/companies/'
    | '/contracts/'
    | '/gigs/'
    | '/learn/'
    | '/locations/'
    | '/me/'
    | '/post/'
    | '/roles/'
    | '/salaries/'
    | '/talent/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  PulseRoute: typeof PulseRoute
  SearchRoute: typeof SearchRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  ApplyJobSlugRoute: typeof ApplyJobSlugRoute
  ChainsSlugRoute: typeof ChainsSlugRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  ContractsSlugRoute: typeof ContractsSlugRoute
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
  GigsSlugRoute: typeof GigsSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  MeProfileRoute: typeof MeProfileRoute
  PostContractRoute: typeof PostContractRoute
  PostGigRoute: typeof PostGigRoute
  PostRoleRoute: typeof PostRoleRoute
  RolesSlugRoute: typeof RolesSlugRoute
  SalariesSlugRoute: typeof SalariesSlugRoute
  ScenesSlugRoute: typeof ScenesSlugRoute
  TalentSlugRoute: typeof TalentSlugRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  GigsIndexRoute: typeof GigsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  PostIndexRoute: typeof PostIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  SalariesIndexRoute: typeof SalariesIndexRoute
  TalentIndexRoute: typeof TalentIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobSlug': {
      id: '/apply/$jobSlug'
      path: '/apply/$jobSlug'
      fullPath: '/apply/$jobSlug'
      preLoaderRoute: typeof ApplyJobSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains/$slug': {
      id: '/chains/$slug'
      path: '/chains/$slug'
      fullPath: '/chains/$slug'
      preLoaderRoute: typeof ChainsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$slug': {
      id: '/contracts/$slug'
      path: '/contracts/$slug'
      fullPath: '/contracts/$slug'
      preLoaderRoute: typeof ContractsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/departments/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/': {
      id: '/gigs/'
      path: '/gigs'
      fullPath: '/gigs/'
      preLoaderRoute: typeof GigsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/$slug': {
      id: '/gigs/$slug'
      path: '/gigs/$slug'
      fullPath: '/gigs/$slug'
      preLoaderRoute: typeof GigsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/contract': {
      id: '/post/contract'
      path: '/post/contract'
      fullPath: '/post/contract'
      preLoaderRoute: typeof PostContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/gig': {
      id: '/post/gig'
      path: '/post/gig'
      fullPath: '/post/gig'
      preLoaderRoute: typeof PostGigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/role': {
      id: '/post/role'
      path: '/post/role'
      fullPath: '/post/role'
      preLoaderRoute: typeof PostRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$slug': {
      id: '/roles/$slug'
      path: '/roles/$slug'
      fullPath: '/roles/$slug'
      preLoaderRoute: typeof RolesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/': {
      id: '/salaries/'
      path: '/salaries'
      fullPath: '/salaries/'
      preLoaderRoute: typeof SalariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/$slug': {
      id: '/salaries/$slug'
      path: '/salaries/$slug'
      fullPath: '/salaries/$slug'
      preLoaderRoute: typeof SalariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes/$slug': {
      id: '/scenes/$slug'
      path: '/scenes/$slug'
      fullPath: '/scenes/$slug'
      preLoaderRoute: typeof ScenesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$slug': {
      id: '/talent/$slug'
      path: '/talent/$slug'
      fullPath: '/talent/$slug'
      preLoaderRoute: typeof TalentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  PulseRoute: PulseRoute,
  SearchRoute: SearchRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  ApplyJobSlugRoute: ApplyJobSlugRoute,
  ChainsSlugRoute: ChainsSlugRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  ContractsSlugRoute: ContractsSlugRoute,
  DepartmentsSlugRoute: DepartmentsSlugRoute,
  GigsSlugRoute: GigsSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  MeProfileRoute: MeProfileRoute,
  PostContractRoute: PostContractRoute,
  PostGigRoute: PostGigRoute,
  PostRoleRoute: PostRoleRoute,
  RolesSlugRoute: RolesSlugRoute,
  SalariesSlugRoute: SalariesSlugRoute,
  ScenesSlugRoute: ScenesSlugRoute,
  TalentSlugRoute: TalentSlugRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  GigsIndexRoute: GigsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  MeIndexRoute: MeIndexRoute,
  PostIndexRoute: PostIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  SalariesIndexRoute: SalariesIndexRoute,
  TalentIndexRoute: TalentIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
